import type { ProductPoint } from "../GlobalFields/ProductPoint";
import type { CommonContentTypeFields } from "./Common";

export type ProductInformation = CommonContentTypeFields & {
  title: string;
  url: string;
  important_notes: string;
  wyltt: string;
  ittrfy: string;
  physical_rating_description: string;
  a_couple_of_rules: string;
  climate_and_seasonal_information: string;
  communications: string;
  feedback: string;
  group_leader: string;
  food_and_dietary_requirements: string;
  itinerary_disclaimer: string;
  medical_and_health_information: string;
  problems_and_emergency_contact_information: string;
  money_matters: string;
  pre_departure_checklist: string;
  accommodation_notes: string;
  packing: string;
  visas: string;
  responsible_travel: string;
  the_intrepid_foundation: string;
  travelling_in_a_group: string;
  safety: string;
  travel_insurance: string;
  transport_notes: string;
  joining_point: ProductPoint;
  finishing_point: ProductPoint;
  continuing_points: ProductPoint[];
  alternate_joining_points: ProductPoint[];
  alternate_finishing_points: ProductPoint[];
  alternate_continuing_points: ProductPoint[];
  included_activities: string[];
  optional_activities: string[];
};
